### ISSUE TITLE
looking forward training and testing code！

### ISSUE THREAD

**Issue by peylnog** [yamand16/ExposureCorrection#1]
Thanks for your excellent work.
looking forward training and testing code！

**Comment by yamand16** [comment]
Thank you for your interest. We are still working on the code and we are going to share ASAP.

**Comment by hackkhai** [comment]
Hey, I am eager to test it out can we get an estimate on this?

**Comment by rebeccaeexu** [comment]
Hi, can't wait the release of training code and pretrained model

**Comment by griffinkelly** [comment]
any updates?

**Comment by msk7131** [comment]
any updates?
