### ISSUE TITLE
Incorrect image and label in line 107 of aligned_dataset.py

### ISSUE THREAD

**Issue by HangLuoWh** [yamand16/ExposureCorrection#7]
According to the training command, file_name_A contains the name of input images and file_name_B corresponds to label images. Thus, in the dictionary produced by class AlignedDataset_for_file, A_tensor should be the input image and B_tensor should be the label.

**Comment by yamand16** [comment]
Hello, thank you for your post. Our code is based on [Pix2PixHD](https://github.com/NVIDIA/pix2pixHD). In Pix2PixHD, the model takes a label as input to generate the image. Therefore, the label represents the input, while the image represents the GT. However, you are right that it might cause confusion.
